//
//  BlitzBuchInfoView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchInfoView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var titleHolderView: UIView!
    @IBOutlet weak var textView: UITextView!
    @IBOutlet weak var titleLabel: UILabel!
    
    // MARK: - Lifecycle
    
    override func layoutSubviews() {
        super.layoutSubviews()
        self.titleHolderView.addBottomBorder(color: .gray, margins: 0, borderLineSize: 0.3)
    }
    
    // MARK: - Public methods
    
    func setup(model: BaseViewModel & BlitzBuchInfoViewModelProtocol) {
        titleLabel.text = model.textModel.titleText
        textView.attributedText = model.textModel.getTextForTextView()
    }
}
