//
//  BlitzBuchInfoViewModel.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BlitzBuchInfoViewModelProtocol {
    var textModel: BlitzBuchInfo.TextModel { get set }
}

class BlitzBuchInfoViewModel: BaseViewModel, BlitzBuchInfoViewModelProtocol {
    
    // MARK: - BlitzBuchInfoViewModelProtocol Vars & Lets
    
    var textModel: BlitzBuchInfo.TextModel

    // MARK: - Init
    
    override init() {
        self.textModel = BlitzBuchInfo.TextModel(titleText: InfoViewData.titleText,
                                                 separatorCustomText: InfoViewData.separatorCustomText,
                                                 firstSectionText: InfoViewData.firstSectionText,
                                                 secondSectionTitle: InfoViewData.secondSectionTitle,
                                                 secondSectionText: InfoViewData.secondSectionText,
                                                 thirdSectionTitle: InfoViewData.thirdSectionTitle,
                                                 thirdSectionText: InfoViewData.thirdSectionText,
                                                 fourthSectionTitle: InfoViewData.fourthSectionTitle,
                                                 fourthSectionText: InfoViewData.fourthSectionText)
        super.init()
    }
    
}
