//
//  BlitzBuchHomeView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchHomeView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var vipButton: UIButton!
    @IBOutlet weak var menuButton: UIButton!
    @IBOutlet weak var imageViewConstraint: NSLayoutConstraint!
    @IBOutlet weak var tableView: UITableView!

    // MARK: - Public methods
    
    func setup(target: Any,
               menuButtonSelector: Selector,
               vipButtonSelector: Selector,
               tableViewDelegate: UITableViewDelegate,
               tableViewDataSource: UITableViewDataSource) {
        let customCellName = String(describing: BookTableViewCell.self)
        tableView.register(UINib(nibName: customCellName, bundle: nil), forCellReuseIdentifier: customCellName)
        
        let customCell = String(describing: BlueCloudCell.self)
        tableView.register(UINib(nibName: customCell, bundle: nil), forCellReuseIdentifier: customCell)
        tableView.delegate = tableViewDelegate
        tableView.dataSource = tableViewDataSource
        
        // Actions
        self.vipButton.addTarget(target, action: vipButtonSelector, for: .touchUpInside)
        self.menuButton.addTarget(target, action: menuButtonSelector, for: .touchUpInside)
    }
}
