//
//  BlitzBuchHomeViewController.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SideMenu
import Firebase
import RxSwift

protocol BlitzBuchHomeViewControllerProtocol: AnyObject {
    
}

class BlitzBuchHomeViewController: BaseViewController, BlitzBuchHomeViewControllerProtocol {
    
    // MARK: - Vars & Lets
    
    private var customView: BlitzBuchHomeView! {
        loadViewIfNeeded()
        return view as? BlitzBuchHomeView
    }
    var viewModel: (BaseViewModel & BlitzBuchHomeViewModelProtocol)?
    var disposeBag = DisposeBag()
    private var sideMenuController: SideMenuViewController?
    
    // MARK: - Controller lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.customView.setup(target: self,
                              menuButtonSelector: #selector(self.menuButtonAction),
                              vipButtonSelector: #selector(self.vipButtonAction),
                              tableViewDelegate: self,
                              tableViewDataSource: self)
        self.viewModel?.fetchLatestBooks()
        self.bindViewModel()
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        self.disposeBag = DisposeBag()
    }
    
    // MARK: - Private methods
    
    private func bindViewModel() {
        self.viewModel?.error.bind({ [weak self] in
            guard let self = self else { return }
            if let error = $0 {
                self.handleError(error: error)
            }
        })
        self.viewModel?.isLoaderHidden.bind({ [weak self] in
            self?.shouldHideLoader(isHidden: $0)
        })
        self.viewModel?.homeBooks.bind({ [weak self] _ in
            self?.customView.tableView.reloadData()
        })
    }
    
    private func addBookToCart(indexPath: IndexPath) {
        if let model = self.viewModel?.homeBooks.value[indexPath.row] {
            if let user = self.viewModel?.userDefaults.getUser() {
                UsersService.getCartBooks(userId: user.id ?? 0).subscribe { (cartBooks) in
                    user.cartItems = ""
                    var userCartBooks = String()
                    cartBooks.forEach({ book in
                        userCartBooks.append("\(book),")
                    })
                    if userCartBooks.last == "," {
                        userCartBooks.removeLast()
                    }
                    user.cartItems = userCartBooks
                    self.viewModel?.userDefaults.saveUser(user)
                    var cartItems = user.cartItems
                    self.navigationController?.view.startActivityIndicator()
                    BooksService.checkLock(bookId: model.id).subscribe { (locked) in
                        if locked == true {
                            if !(cartItems?.contains(String(model.id)) ?? false) {
                                self.getAlert(errorString: NSLocalizedString("Book is already reserved", comment: ""), errorColor: Colors.orange)
                            } else {
                                self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                            }
                        } else {
                            if model.vip == true {
                                guard let id = user.id else {return}
                                UsersService.checkForAvailableBooks(id).subscribe {(vip, regular) in
                                    let vip = vip
                                    let regular = regular
                                    if vip > 0 {
                                        self.updateVipBooksNumber(removeBooks: true, numberOfBooks: 1, disposeBag: self.disposeBag)
                                        if !(cartItems?.contains(String(model.id)) ?? false) {
                                            user.numberOfRegularBooks = regular
                                            self.getAlert(errorString: NSLocalizedString("Book is added to cart", comment: ""), errorColor: Colors.blueDefault)
                                            model.locked = LockStatus.locked.rawValue
                                            cartItems?.append(String(model.id))
                                            BooksService.lockBook(bookId: model.id, lockStatus: .locked).subscribe { [weak self] (finished) in
                                                let lockedBookId = (String(model.id))
                                                self?.lockedBooks.append(lockedBookId)
                                                var cartBooks = [String]()
                                                user.cartItems?.components(separatedBy: ",").forEach({ component in
                                                    cartBooks.append(component)
                                                })
                                                cartBooks.append(lockedBookId)
                                                var newCartBooks = cartBooks
                                                newCartBooks = Array(Set(newCartBooks))
                                                let clearBooksArray = newCartBooks.filter({return $0 != ""})
                                                var cartItemsCleared = String()
                                                clearBooksArray.forEach({ item in
                                                    cartItemsCleared.append("\(item),")
                                                })
                                                if cartItemsCleared.last == "," {
                                                    cartItemsCleared.removeLast()
                                                }
                                                user.cartItems = cartItemsCleared
                                                self?.viewModel?.userDefaults.saveUser(user)
                                                UsersService.updateCartBooks(userId: id, bookIDs: clearBooksArray).subscribe { (subscribed) in
                                                    //
                                                } onError: { (error) in
                                                    self?.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                                } onCompleted: {
                                                    //
                                                }.disposed(by: self?.disposeBag ?? DisposeBag())
                                                
                                            } onError: { (error) in
                                                self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                            } onCompleted: {
                                                //
                                            } onDisposed: {
                                                //
                                            }.disposed(by: self.disposeBag)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        }
                                        
                                    } else {
                                        if (cartItems?.contains(String(model.id)) ?? false) {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("You have used the limit for vip books", comment: ""), errorColor: Colors.orange)
                                        }
                                    }
                                    
                                } onError: { (error) in
                                    self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                } onCompleted: {
                                    //
                                } onDisposed: {
                                    //
                                }.disposed(by: self.disposeBag)
                            }
                            if model.vip == false {
                                guard let id = user.id else {return}
                                UsersService.checkForAvailableBooks(id).subscribe {(vip, regular) in
                                    let regular = regular
                                    if regular > 0 {
                                        self.updateBooksNumber(removeBooks: true, numberOfBooks: 1, disposeBag: self.disposeBag)
                                        if !(cartItems?.contains(String(model.id)) ?? false) {
                                            user.numberOfRegularBooks = regular
                                            self.getAlert(errorString: NSLocalizedString("Book is added to cart", comment: ""),
                                                          errorColor: Colors.blueDefault)
                                            model.locked = LockStatus.locked.rawValue
                                            cartItems?.append("\(String(model.id)),")
                                            BooksService.lockBook(bookId: model.id, lockStatus: .locked).subscribe { [weak self] (finished) in
                                                let lockedBookId = (String(model.id))
                                                self?.lockedBooks.append(lockedBookId)
                                                var cartBooks = [String]()
                                                user.cartItems?.components(separatedBy: ",").forEach({ component in
                                                    cartBooks.append(component)
                                                })
                                                cartBooks.append(lockedBookId)
                                                var newCartBooks = cartBooks
                                                newCartBooks = Array(Set(newCartBooks))
                                                let clearBooksArray = newCartBooks.filter({return $0 != ""})
                                                var cartItemsCleared = String()
                                                clearBooksArray.forEach({ item in
                                                    cartItemsCleared.append("\(item),")
                                                })
                                                if cartItemsCleared.last == "," {
                                                    cartItemsCleared.removeLast()
                                                }
                                                user.cartItems = cartItemsCleared
                                                self?.viewModel?.userDefaults.saveUser(user)
                                                UsersService.updateCartBooks(userId: id, bookIDs: clearBooksArray).subscribe { (subscribed) in
                                                    //
                                                } onError: { (error) in
                                                    self?.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                                } onCompleted: {
                                                    //
                                                }.disposed(by: self?.disposeBag ?? DisposeBag())
                                                
                                            } onError: { (error) in
                                                self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                            } onCompleted: {
                                                //
                                            } onDisposed: {
                                                //
                                            }.disposed(by: self.disposeBag)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        }
                                    } else {
                                        if (cartItems?.contains(String(model.id)) ?? false) {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("You have used the limit for regular books", comment: ""), errorColor: Colors.orange)
                                        }
                                    }
                                } onError: { (error) in
                                    self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                } onCompleted: {
                                    //
                                } onDisposed: {
                                    //
                                }.disposed(by: self.disposeBag)
                            }
                        }
                        self.navigationController?.view.stopActivityIndicator()
                    } onError: { (error) in
                        self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                    } onCompleted: {
                        //
                    } onDisposed: {
                        //
                    }.disposed(by: self.disposeBag)
                    
                    do {
                        try DataManager.shared.context.save()
                    } catch {
                        self.getAlert(errorString: "Error saving data", errorColor: Colors.orange)
                    }
                } onError: { (error) in
                    self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                } onCompleted: {
                    //
                } onDisposed: {
                    //
                }.disposed(by: self.disposeBag)
            }
        }
    }
}

// MARK: - UITableViewDelegate, UITableViewDataSource

extension BlitzBuchHomeViewController: UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 {
            return self.viewModel?.homeBooks.value.count ?? 0
        } else {
            return 1
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 1 {
            let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: BlueCloudCell.self), for: indexPath) as! BlueCloudCell
            return cell
        } else {
            let model = self.viewModel?.homeBooks.value[indexPath.row]
            let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: BookTableViewCell.self), for: indexPath) as! BookTableViewCell
            if let item = model  {
                cell.set(with: item, inVipController: false)
                cell.indexPath = indexPath
                cell.cellDelegate = self
                cell.delegate = self
                return cell
            }
        }
        return UITableViewCell()
    }
    
    @objc func alert () {
        let newAlert = UIAlertController(title: "NOVI", message: "CONTROLLER", preferredStyle: .alert)
        present(newAlert, animated: true)
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        var height = CGFloat()
        if indexPath.section == 0{
            height = 182
        } else {
            height = 200
        }
        return height
    }
}

// MARK: - Actions

extension BlitzBuchHomeViewController {
    @objc private func menuButtonAction() {
        if let vc = (UIApplication.shared.delegate as? AppDelegate)?.getSideMenu() {
            let menu = SideMenuNavigationController(rootViewController: vc)
            menu.leftSide = true
            if self.traitCollection.userInterfaceStyle == .dark {
                menu.settings.blurEffectStyle = .systemMaterialDark
            } else {
                menu.settings.blurEffectStyle = .systemMaterialLight
            }
            menu.pushStyle = .default
            menu.presentationStyle = .menuSlideIn
            menu.presentationStyle.menuOnTop = true
            menu.menuWidth = self.view.frame.size.width * 0.8
            menu.presentationStyle.presentingEndAlpha = 0.5
            menu.statusBarEndAlpha = 0
            menu.presentationStyle.onTopShadowOffset = CGSize(width: 3, height: 0)
            menu.enableSwipeToDismissGesture = true
            menu.dismissWhenBackgrounded = true
            vc.navigationController?.setNavigationBarHidden(true, animated: false)
            present(menu, animated: true, completion: nil)
        }
    }
    
    @objc private func vipButtonAction() {
        if let tabController = UIApplication.shared.windows.first?.rootViewController as? TabBarViewController {
            tabController.view.backgroundColor = Colors.defaultBackgroundColor
            if let vc = tabController.viewControllers?[2] {
                _ = tabController.tabBarController(tabController, shouldSelect: vc)
                vc.presentedViewController?.dismiss(animated: true, completion: nil)
                if let vc = vc as? UINavigationController {
                    vc.popToRootViewController(animated: true)
                }
            }
        }
    }
}


extension BlitzBuchHomeViewController: AlertMe {
    func onClick() {
    }
    
    func onLoggedOutClick() {
        let alertVC = self.alertService.alert()
        self.present(alertVC, animated: true)
    }
    
}

// MARK: - CellDelegate

extension BlitzBuchHomeViewController: SelectedBookDelegate {
    func bookSelected(indexPath: IndexPath) {
        self.addBookToCart(indexPath: indexPath)
    }
}

