//
//  BlitzBuchGenreModels.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 28.8.21..
//  Copyright (c) 2021 Upgrade Technology DOO. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BlitzBuchGenre {
    
}
