//
//  BlitzBuchGenreView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 28.8.21..
//  Copyright (c) 2021 Upgrade Technology DOO. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchGenreView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var holderView: UIView!
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var donateTitleLabel: UILabel!
    @IBOutlet weak var donateTextLabel: UILabel!
    
    // MARK: - Lifecycle
    
    override func layoutSubviews() {
        super.layoutSubviews()
        self.holderView.addBottomBorder(color: .gray, margins: 0, borderLineSize: 0.3)
    }

    // MARK: - Public methods
    
    func setup(target: Any,
               tableViewDelegate: UITableViewDelegate,
               tableViewDataSource: UITableViewDataSource) {
        self.tableView.delegate = tableViewDelegate
        self.tableView.dataSource = tableViewDataSource
        let customCellName = String(describing: BookTableViewCell.self)
        self.tableView.register(UINib(nibName: customCellName, bundle: nil), forCellReuseIdentifier: customCellName)
        self.tableView.tableFooterView = UIView()
        
        // Set text
        self.donateTitleLabel.text = "Why donation...".localized()
        self.donateTextLabel.text = "Expansion of the range of book titles,\nfunding and creation of an increasingly \nbeing mobile application,\nIn addition to Belletristic also offer of\neniclopedia editions and specialist literature".localized()
        
    }
}
