//
//  BlitzBuchLibraryView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchLibraryView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var borderView: UIView!
    @IBOutlet weak var genreTable: UITableView!
    
    // MARK: - Lifecycle
    
    override func layoutSubviews() {
        super.layoutSubviews()
        self.borderView.addBottomBorder(color: .gray, margins: 0, borderLineSize: 0.3)
    }

    // MARK: - Public methods
    
    func setup(target: Any,
               tableViewDelegate: UITableViewDelegate,
               tableViewDataSource: UITableViewDataSource) {
        
        // Configure table
        if let path = genreTable.indexPathForSelectedRow {
            genreTable.deselectRow(at: path, animated: true)
        }
        self.genreTable.dataSource = tableViewDataSource
        self.genreTable.delegate = tableViewDelegate
        let customCellName = String(describing: CategoryTableViewCell.self)
        genreTable.register(UINib(nibName: customCellName, bundle: nil), forCellReuseIdentifier: customCellName)
        genreTable.tableFooterView = UIView()
    }
}
