//
//  BlitzBuchLibraryViewModel.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BlitzBuchLibraryViewModelProtocol {
    var genre: Book.Genre { get set }
    var dataSource: Dynamic<[String]> { get set }
    var indexNumber: Int { get set }
}

class BlitzBuchLibraryViewModel: BaseViewModel, BlitzBuchLibraryViewModelProtocol {
    
    // MARK: - BlitzBuchLibraryViewModelProtocol Vars & Lets

    var genre: Book.Genre = .avantura
    var dataSource: Dynamic<[String]>
    var indexNumber: Int = 0
    
    // MARK: - Init
    
    override init() {
        self.dataSource = Dynamic([NSLocalizedString("Adventure", comment: ""),
                                   NSLocalizedString("Biography", comment: ""),
                                   NSLocalizedString("Detective novels / crime novels", comment: ""),
                                   NSLocalizedString("The epic fantasy", comment: ""),
                                   NSLocalizedString("Erotic novels / romance novels", comment: ""),
                                   NSLocalizedString("Classical Literature", comment: ""),
                                   NSLocalizedString("Popular Psychology", comment: ""),
                                   NSLocalizedString("Thriller", comment: ""),
                                   NSLocalizedString("Historical novels", comment: ""),
                                   NSLocalizedString("Miscellaneous", comment: ""),
                                   NSLocalizedString("Horror", comment: ""),
                                   NSLocalizedString("Action", comment: ""),
                                   NSLocalizedString("Novel", comment: "")].sorted())
        super.init()
    }
    
}
