//
//  BlitzBuchCartModels.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 28.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Enums

enum BlitzBuchCart {
    
    // MARK: - Enum
    
    enum TransportExpences: String, CaseIterable {
        case transport = "club.blitzBuch.transport"
    }

}
