//
//  BlitzBuchCartView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 28.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchCartView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Public methods
    
    func setup(target: Any,
               tableViewDelegate: UITableViewDelegate,
               tableViewDataSource: UITableViewDataSource) {
        self.tableView.delegate = tableViewDelegate
        self.tableView.dataSource = tableViewDataSource
        self.configureTable()
    }
    
    // MARK: - Private methods

    private func configureTable(){
        let customCellName = String(describing: BookTableViewCell.self)
        let orderCellName = String(describing: OrderTableViewCell.self)
        tableView?.register(UINib(nibName: customCellName, bundle: nil), forCellReuseIdentifier: customCellName)
        tableView?.register(UINib(nibName: orderCellName, bundle: nil), forCellReuseIdentifier: orderCellName)
        tableView?.register(UINib(nibName: String(describing: EmptyTableViewCell.self), bundle: nil), forCellReuseIdentifier: String(describing: EmptyTableViewCell.self))
        self.tableView?.tableFooterView = UIView()
    }
}
