//
//  BlitzBuchLoginView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchLoginView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var loginEmailTextField: UITextField!
    @IBOutlet weak var loginPasswordTextField: UITextField!
    @IBOutlet private weak var loginButton: UIButton!
    @IBOutlet private weak var registerButton: UIButton!
    
    // MARK: - Vars & Lets
    
    private var deviceType : DeviceType?

    // MARK: - Public methods
    
    func setup(target: Any,
               loginButtonSelector: Selector,
               registerButtonSelector: Selector) {
        self.styleViews()
        
        // Actions
        self.loginButton.addTarget(target, action: loginButtonSelector, for: .touchUpInside)
        self.registerButton.addTarget(target, action: registerButtonSelector, for: .touchUpInside)
    }
    
    func styleViews(){
        deviceType = self.getDeviceType()
        loginButton.layer.cornerRadius = CornerRadius.medium
        loginButton.backgroundColor = deviceType != .macCatalyst ? Colors.blueDefault : .clear
        loginButton.setTitle(NSLocalizedString("Login", comment: ""), for: .normal)
        loginButton.setTitleColor(deviceType != .macCatalyst ? Colors.white : Colors.defaultFontColor, for: .normal)
        registerButton.setAttributedTitle(NSAttributedString(string: "Register".localized()), for: .normal)
    }
}
