//
//  BlitzBuchLoginViewController.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PopupDialog

protocol BlitzBuchLoginViewControllerProtocol: AnyObject {
    var onLoggedIn: (() -> Void)? { get set }
    var onRegister: (() -> Void)? { get set }
}

class BlitzBuchLoginViewController: BaseViewController, BlitzBuchLoginViewControllerProtocol {
    
    // MARK: - BlitzBuchLoginViewControllerProtocol Vars & Lets
    
    var onLoggedIn: (() -> Void)?
    var onRegister: (() -> Void)?

    // MARK: - Vars & Lets
    
    var customView: BlitzBuchLoginView! {
        return view as? BlitzBuchLoginView
    }
    var viewModel: (BaseViewModel & BlitzBuchLoginViewModelProtocol)?
    
    // MARK: - Controller lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.title = "Login".localized()
        self.customView?.setup(target: self,
                               loginButtonSelector: #selector(self.loginButtonPressed),
                               registerButtonSelector: #selector(self.registerButtonPressed))
        self.bindViewModel()
    }
    
    // MARK: - Private methods
    
    private func bindViewModel() {
        self.viewModel?.error.bind({ [weak self] in
            if let error = $0 {
                self?.handleError(error: error)
            }
        })
        self.viewModel?.isLoaderHidden.bind({ [weak self] in
            self?.shouldHideLoader(isHidden: $0)
        })
        self.viewModel?.loggedIn.bind({ [weak self] _ in
            self?.viewModel?.navigateToHome()
        })
    }
    
}

// MARK: - Actions

extension BlitzBuchLoginViewController {
    @objc func loginButtonPressed() {
        self.viewModel?.validateData(email: self.customView?.loginEmailTextField.text ?? "",
                                     password: self.customView?.loginPasswordTextField.text ?? "")
    }
    
    @objc func registerButtonPressed() {
        self.onRegister?()
    }
}

