//
//  BlitzBuchSearchView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchSearchView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var searchTable: UITableView!
    @IBOutlet weak var viewForBorder: UIView!
    @IBOutlet weak var label: UILabel!
    @IBOutlet weak var searchBar1: UISearchBar!
    @IBOutlet weak var sugestionsLabel: UILabel!
    
    // MARK: - Public methods
    
    override func layoutSubviews() {
        super.layoutSubviews()
        searchBar1.text = ""
        self.sugestionsLabel.alpha = 1
    }
    
    func setup(target: Any,
               tableViewDelegate: UITableViewDelegate,
               tableViewDataSource: UITableViewDataSource,
               searchBarDelegate: UISearchBarDelegate) {
        searchTable.delegate = tableViewDelegate
        searchTable.dataSource = tableViewDataSource
        searchBar1.delegate = searchBarDelegate
        let customCellName = String(describing: BookTableViewCell.self)
        searchTable.register(UINib(nibName: customCellName, bundle: nil), forCellReuseIdentifier: customCellName)
    }
}
