//
//  BlitzBuchSearchViewController.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol BlitzBuchSearchViewControllerProtocol: AnyObject {
    
}

class BlitzBuchSearchViewController: BaseViewController, BlitzBuchSearchViewControllerProtocol {
    
    // MARK: - Vars & Lets
    
    private var customView: BlitzBuchSearchView! {
        loadViewIfNeeded()
        return view as? BlitzBuchSearchView
    }
    var viewModel: (BaseViewModel & BlitzBuchSearchViewModelProtocol)?
    var disposeBag = DisposeBag()
    
    // MARK: - Controller lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.viewModel?.fetch()
        self.viewModel?.fetchRecommendedBooks()
        self.customView.searchTable.reloadData()
        self.customView.setup(target: self,
                              tableViewDelegate: self,
                              tableViewDataSource: self,
                              searchBarDelegate: self,
                              searchBarClearButtonSelector: #selector(self.resignKeyboard))
        self.bindViewModel()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.viewModel?.fetch()
        self.viewModel?.fetchRecommendedBooks()
        if let viewModel = self.viewModel {
            viewModel.fetch()
            viewModel.fetchRecommendedBooks()
            viewModel.mainFilteredData.value = viewModel.dataSource.value
            viewModel.filteredDataSource.value = viewModel.weRecommend.value
        }
    }
    
    
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        self.disposeBag = DisposeBag()
    }
    
    // MARK: - Private methods
    
    private func bindViewModel() {
        self.viewModel?.error.bind({ [weak self] in
            if let error = $0 {
                self?.handleError(error: error)
            }
        })
        self.viewModel?.isLoaderHidden.bind({ [weak self] in
            self?.shouldHideLoader(isHidden: $0)
        })
        self.viewModel?.dataSource.bind({ [weak self] _ in
            self?.customView.searchTable.reloadData()
        })
        self.viewModel?.weRecommend.bind({ [weak self] _ in
            self?.customView.searchTable.reloadData()
        })
        self.viewModel?.filteredDataSource.bind({ [weak self] _ in
            self?.customView.searchTable.reloadData()
        })
    }
    
    private func addBookToCart(indexPath: IndexPath) {
        if let model = self.viewModel?.filteredDataSource.value[indexPath.row] {
            if let user = self.viewModel?.userDefaults.getUser() {
                self.navigationController?.view.startActivityIndicator()
                UsersService.getCartBooks(userId: user.id ?? 0).subscribe { (cartBooks) in
                    user.cartItems = ""
                    var userCartBooks = String()
                    cartBooks.forEach({ book in
                        userCartBooks.append("\(book),")
                    })
                    if userCartBooks.last == "," {
                        userCartBooks.removeLast()
                    }
                    user.cartItems = userCartBooks
                    self.viewModel?.userDefaults.saveUser(user)
                    var cartItems = user.cartItems
                    self.navigationController?.view.startActivityIndicator()
                    BooksService.checkLock(bookId: model.id).subscribe { (locked) in
                        if locked == true {
                            if !(cartItems?.contains(String(model.id)) ?? false) {
                                self.getAlert(errorString: NSLocalizedString("Book is already reserved", comment: ""), errorColor: Colors.orange)
                            } else {
                                self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                            }
                        } else {
                            if model.vip == true {
                                guard let id = user.id else {return}
                                UsersService.checkForAvailableBooks(id).subscribe {(vip, regular) in
                                    let vip = vip
                                    let regular = regular
                                    if vip > 0 {
                                        self.updateVipBooksNumber(removeBooks: true, numberOfBooks: 1, disposeBag: self.disposeBag)
                                        if !(cartItems?.contains(String(model.id)) ?? false) {
                                            user.numberOfRegularBooks = regular
                                            self.getAlert(errorString: NSLocalizedString("Book is added to cart", comment: ""), errorColor: Colors.blueDefault)
                                            model.locked = LockStatus.locked.rawValue
                                            cartItems?.append(String(model.id))
                                            BooksService.lockBook(bookId: model.id, lockStatus: .locked).subscribe { [weak self] (finished) in
                                                let lockedBookId = (String(model.id))
                                                self?.lockedBooks.append(lockedBookId)
                                                var cartBooks = [String]()
                                                user.cartItems?.components(separatedBy: ",").forEach({ component in
                                                    cartBooks.append(component)
                                                })
                                                cartBooks.append(lockedBookId)
                                                var newCartBooks = cartBooks
                                                newCartBooks = Array(Set(newCartBooks))
                                                let clearBooksArray = newCartBooks.filter({return $0 != ""})
                                                var cartItemsCleared = String()
                                                clearBooksArray.forEach({ item in
                                                    cartItemsCleared.append("\(item),")
                                                })
                                                if cartItemsCleared.last == "," {
                                                    cartItemsCleared.removeLast()
                                                }
                                                user.cartItems = cartItemsCleared
                                                self?.viewModel?.userDefaults.saveUser(user)
                                                UsersService.updateCartBooks(userId: id, bookIDs: clearBooksArray).subscribe { (subscribed) in
                                                    self?.navigationController?.view.stopActivityIndicator()
                                                    //
                                                } onError: { (error) in
                                                    self?.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                                } onCompleted: {
                                                    //
                                                }.disposed(by: self?.disposeBag ?? DisposeBag())
                                                
                                            } onError: { (error) in
                                                self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                            } onCompleted: {
                                                //
                                            } onDisposed: {
                                                //
                                            }.disposed(by: self.disposeBag)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        }
                                        
                                    } else {
                                        if (cartItems?.contains(String(model.id)) ?? false) {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("You have used the limit for vip books", comment: ""), errorColor: Colors.orange)
                                        }
                                    }
                                    
                                } onError: { (error) in
                                    self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                } onCompleted: {
                                    //
                                } onDisposed: {
                                    //
                                }.disposed(by: self.disposeBag)
                            }
                            if model.vip == false {
                                guard let id = user.id else {return}
                                UsersService.checkForAvailableBooks(id).subscribe {(vip, regular) in
                                    let regular = regular
                                    if regular > 0 {
                                        self.updateBooksNumber(removeBooks: true, numberOfBooks: 1, disposeBag: self.disposeBag)
                                        if !(cartItems?.contains(String(model.id)) ?? false) {
                                            user.numberOfRegularBooks = regular
                                            self.getAlert(errorString: NSLocalizedString("Book is added to cart", comment: ""),
                                                          errorColor: Colors.blueDefault)
                                            model.locked = LockStatus.locked.rawValue
                                            cartItems?.append("\(String(model.id)),")
                                            BooksService.lockBook(bookId: model.id, lockStatus: .locked).subscribe { [weak self] (finished) in
                                                let lockedBookId = (String(model.id))
                                                self?.lockedBooks.append(lockedBookId)
                                                var cartBooks = [String]()
                                                user.cartItems?.components(separatedBy: ",").forEach({ component in
                                                    cartBooks.append(component)
                                                })
                                                cartBooks.append(lockedBookId)
                                                var newCartBooks = cartBooks
                                                newCartBooks = Array(Set(newCartBooks))
                                                let clearBooksArray = newCartBooks.filter({return $0 != ""})
                                                var cartItemsCleared = String()
                                                clearBooksArray.forEach({ item in
                                                    cartItemsCleared.append("\(item),")
                                                })
                                                if cartItemsCleared.last == "," {
                                                    cartItemsCleared.removeLast()
                                                }
                                                user.cartItems = cartItemsCleared
                                                self?.viewModel?.userDefaults.saveUser(user)
                                                UsersService.updateCartBooks(userId: id, bookIDs: clearBooksArray).subscribe { (subscribed) in
                                                    self?.navigationController?.view.stopActivityIndicator()
                                                    //
                                                } onError: { (error) in
                                                    self?.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                                } onCompleted: {
                                                    //
                                                }.disposed(by: self?.disposeBag ?? DisposeBag())
                                                
                                            } onError: { (error) in
                                                self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                            } onCompleted: {
                                                //
                                            } onDisposed: {
                                                //
                                            }.disposed(by: self.disposeBag)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        }
                                    } else {
                                        if (cartItems?.contains(String(model.id)) ?? false) {
                                            self.getAlert(errorString: NSLocalizedString("Book is already in cart", comment: ""), errorColor: Colors.orange)
                                        } else {
                                            self.getAlert(errorString: NSLocalizedString("You have used the limit for regular books", comment: ""), errorColor: Colors.orange)
                                        }
                                    }
                                } onError: { (error) in
                                    self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                                } onCompleted: {
                                    //
                                } onDisposed: {
                                    //
                                }.disposed(by: self.disposeBag)
                            }
                        }
                        self.navigationController?.view.stopActivityIndicator()
                    } onError: { (error) in
                        self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                    } onCompleted: {
                        //
                    } onDisposed: {
                        //
                    }.disposed(by: self.disposeBag)
                    
                    do {
                        try DataManager.shared.context.save()
                    } catch {
                        self.getAlert(errorString: "Error saving data", errorColor: Colors.orange)
                    }
                } onError: { (error) in
                    self.getAlert(errorString: error.localizedDescription, errorColor: Colors.orange)
                } onCompleted: {
                    //
                } onDisposed: {
                    //
                }.disposed(by: self.disposeBag)
            }
        }
    }
    
    // MARK: - Action
    
    @objc private func resignKeyboard() {
        self.customView.searchBar1.endEditing(true)
    }
    
    
}

// MARK: - UITableViewDelegate, UITableViewDataSource

extension BlitzBuchSearchViewController: UITableViewDelegate, UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if self.viewModel?.searching.value == false {
            return self.viewModel?.weRecommend.value.count ?? 0
        } else {
            return self.viewModel?.filteredDataSource.value.count ?? 0
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: BookTableViewCell.self),
                                                    for: indexPath) as? BookTableViewCell {
            if let item = self.viewModel?.filteredDataSource.value[indexPath.row] {
                cell.set(with: item, inVipController: false)
                cell.indexPath = indexPath
                cell.delegate = self
            }
            return cell
        }
        return UITableViewCell()
    }
}

// MARK: - AlertMe delegate

extension BlitzBuchSearchViewController: AlertMe {
    func onClick() {
    }
    
    func onLoggedOutClick() {
        let alertVC = self.alertService.alert()
        self.present(alertVC, animated: true)
    }
}

// MARK: - SearchBar Delegate

extension BlitzBuchSearchViewController: UISearchResultsUpdating, UISearchBarDelegate {
    func configureSearch(){
        let search = UISearchController(searchResultsController: nil)
        search.searchBar.delegate = self.customView.searchBar1.delegate
    }
    
    func updateSearchResults(for searchController: UISearchController) {
        guard let text = searchController.searchBar.text else {return}
        print(text)
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        if searchBar.text != "" {
            self.viewModel?.searching.value = true
            self.customView.sugestionsLabel.alpha = 0
            self.viewModel?.filteredDataSource.value = self.viewModel!.mainFilteredData.value.filter({ (book) -> Bool in
                guard let text = searchBar.text else { return false }
                return (book.title?.uppercased().contains(text.uppercased()))!
            })
        } else {
            if let viewModel = self.viewModel {
                viewModel.searching.value = false
                self.customView.sugestionsLabel.alpha = 1
                viewModel.filteredDataSource.value = viewModel.weRecommend.value
            }
        }
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        searchBar.endEditing(true)
    }
    
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        searchBar.endEditing(true)
    }
}

// MARK: - CellDelegate

extension BlitzBuchSearchViewController: SelectedBookDelegate {
    func bookSelected(indexPath: IndexPath) {
        self.addBookToCart(indexPath: indexPath)
    }
}

