//
//  BlitzBuchRegisterModels.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 28.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Enum

enum BlitzBuchRegister {
    
    // MARK: - Models
    
    struct UserModel: Codable {
        var id: Int32?
        var address: String?
        var city: String?
        var email: String?
        var uid: String?
        var name: String?
        var password: String?
        var payment: Bool?
        var phoneNumber: String?
        var vipUser: Bool?
        var numberOfVipBooks: Int?
        var numberOfRegularBooks: Int?
        var cartItems: String?
        var orderedItems: String?
    }
}
