//
//  BlitzBuchRegisterModels.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 28.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Enum

enum BlitzBuchRegister {
    
    // MARK: - Models
    
    struct UserModel: Codable {
        var id: String?
        var uid: String?
        var address: String?
        var city: String?
        var email: String?
        var name: String?
        var password: String?
        var payment: Bool? = false
        var phoneNumber: String?
        var vipUser: Bool? = false
        var numberOfVipBooks: Int? = 0
        var numberOfRegularBooks: Int? = 0
        var cartItems: String? = ""
    }
    
    // MARK: - Enum
    
    enum SubscriptionType: String, CaseIterable {
        case starter = "club.blitzBuch.starter"
        case regular = "club.blitzBuch.regular"
        case vip = "club.blitzBuch.vip"
    }

}
