//
//  BlitzBuchVipView.swift
//  blitzBuch
//
//  Created by Vladimir Sukanica on 17.7.21..
//  Copyright (c) 2021 Vladimir Sukanica. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BlitzBuchVipView: UIView {
    
    // MARK: - Outlets
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var titleHolderView: UIView!
    
    // MARK: - Lifecycle
    
    override func layoutSubviews() {
        super.layoutSubviews()
        titleHolderView.addBottomBorder(color: .gray, margins: 0, borderLineSize: 0.3)
    }
    
    // MARK: - Public methods
    
    func setup(target: Any,
               tableViewDelegate: UITableViewDelegate,
               tableViewDataSource: UITableViewDataSource,
               title: String) {
        self.titleLabel.text = title
        
        // Configure table
        let customCellName = String(describing: BookTableViewCell.self)
        self.tableView.register(UINib(nibName: customCellName, bundle: nil), forCellReuseIdentifier: customCellName)
        self.tableView.delegate = tableViewDelegate
        self.tableView.dataSource = tableViewDataSource
        self.tableView.estimatedRowHeight = 182
    }
}
